- name: show return value of command module
  hosts: server1
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
      #to capture output
    - debug: msg="logged in as user {{ login.stdout }}"
